### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by fabpiaf** [RoblabWh/argus#11]
https://github.com/RoblabWh/argus/blob/80d7f6105b7843ef7669ecf6de13c9017a3a55ab/app/templates/webODM.html#L153
you probably meant "sent"

sorry :unamused: 
![image](https://github.com/user-attachments/assets/3ad29538-e3e2-4604-ba13-6a5b9c708a35)

**Comment by SchulteM42** [comment]
I didn't just mean 'sent' instead of 'send'; I also meant 'successfully' instead of 'successfuly'. :smile:  I fixed it
![spelling-error-meme](https://github.com/user-attachments/assets/6e07cd4e-b050-4d02-857e-c5168dd63853)
