### ISSUE TITLE
Fehler bei der Installation: argus exited with code 1

### ISSUE THREAD

**Issue by m0uu** [RoblabWh/argus#3]
argus            | Traceback (most recent call last):
argus            |   File "/app/main.py", line 27, in <module>
argus            |     main()
argus            |   File "/app/main.py", line 20, in main
argus            |     server = ArgusServer("0.0.0.0", 5000, project_manager, nodeodm_manager, webodm_manager, detection_manager)
argus            |   File "/app/server.py", line 54, in __init__
argus            |     self.thermal_analyser = ThermalAnalyser(project_manager)
argus            |   File "/app/thermal/thermal_analyser.py", line 17, in __init__
argus            |     self.thermal = Thermal(
argus            |   File "/app/thermal/thermal.py", line 415, in __init__
argus            |     assert path.exists(dirp_filename)
argus            | AssertionError

**Comment by SchulteM42** [comment]
The issue should now be resolved, some SDK files were missing in the repository.
