### ISSUE TITLE
Optimizing Image Processing Efficiency in Drone Operations through GPS Threshold Filtering

### ISSUE THREAD

**Issue by NiklasVoigt** [RoblabWh/argus#6]
In stressful situations, it can easily happen that images from previous missions are mistakenly selected from the drone's SD card. This causes Argus to process for a very long time and possibly not complete the task. In our case, two images from a scenario more than 20 km away were mistakenly selected. However, a GPS threshold could help automatically filter out these incorrect images, provide a warning, and thus make the process more efficient.

**Comment by SchulteM42** [comment]
A new filter based on file creation time has been implemented to prevent this. A GPS-based approach seems overkill, but can be added in the future if necessary.
