### ISSUE TITLE
unknown shorthand flag: f with fix on Arch

### ISSUE THREAD

**Issue by fabpiaf** [RoblabWh/argus#8]
https://github.com/RoblabWh/argus/blob/80d7f6105b7843ef7669ecf6de13c9017a3a55ab/argus.sh#L48

on Arch Linux it seems to be `docker-compose` instead of `docker compose`

otherwise: https://github.com/docker/compose/issues/8986 is hit (unknown shorthand flag: f )

**Comment by NiklasVoigt** [comment]
I am using Manjaro with the following versions installed:

$ pacman -Ss docker

extra/docker 1:27.3.1-1 [installed]
and
extra/docker-compose 2.31.0-1 [installed]

With these versions, I am not experiencing any issues. Please ensure that you are running the latest versions as this might resolve the problem.

**Comment by fabpiaf** [comment]
Ah interesting - the problem seemed to be a `.docker/cli-plugins/compose`
I don't actually know where it came from; surely it was not managed by pacman...
